### PR TITLE
Feature request: add "-C" option to "ecal_mon --proto | --echo" (#236)

### PR DESCRIPTION
**Pull request by schilasky**

### CODE REVIEW

**Review by FlorianReimold — APPROVED** [review]
Looks good to me. I first stumbled upon the exact (un) equality comparison `cnt != 0` with cnt being decremented in a different thread, but the way it is implemented in the thread it should work perfectly.

**Comment by rex-schilasky** [comment]
> Looks good to me. I first stumbled upon the exact (un) equality comparison `cnt != 0` with cnt being decremented in a different thread, but the way it is implemented in the thread it should work perfectly.

Yes, maybe there are better way to do it but I test for all possible values of the new ```--count``` argument and it is working as expected in all cases.

**Comment by FlorianReimold** [comment]
A topic with a high frequency will cause more messages to be received, as the cnt variable is only checked every 500ms. But I cannot image anybout caring about that.

**Comment by rex-schilasky** [comment]
No, inside the receive thread (lambda) the ```cnt``` variable is checked and decreased with every message. That thread will stop printing out if the number of received messages reached ```cnt```. The main thread then will exit with a maximum delay of 500 ms checking the same variable of zero.

**Pull request merged**
