### PR TITLE
Enable ASAN compiler options with ECAL tests

### PR DESCRIPTION
**Pull request by phongt**
This is the first step for enable AddressSanitizer for checking memory issue [1] .Please give feedback.

After applying, detected some mem leak  in the ecore_test some memleak issues still in investigation.

[1] https://github.com/google/sanitizers/wiki/AddressSanitizer

### CODE REVIEW

**Comment by rex-schilasky** [comment]
@phongt thank you for your contribution. This is very welcome. Looking forward to the results.

**Comment by FlorianReimold** [comment]
Hi @phongt,

Thank you very much for this awesome analysis! At the moment you only added one line of code in ecal_thread.cpp, where you closed an event. I hardly believe that this is everything asan will bring up ;-)
What else did it show? Are you still investigating the other issues?

Regards
Florian

**Comment by phongt** [comment]
Hello @FlorianReimold 
>What else did it show? 

There are a lot of failure of unit tests,
In the run test step of github actions [1].
I did a options in CMakeLists.txt for enable/disable the ASAN build in 4031a70

>Are you still investigating the other issues?

I am checking 1 case ecal_test_core_cpp: Core.LeakedPubSub but look like this testcase is leak as intention 



[1] https://github.com/continental/ecal/runs/3026981560

**Comment by rex-schilasky** [comment]
The single documented leak in ecal_thread.cpp (gCloseEvent) is fixed in separate PR #388. Changes in CMakeLists.txt can not be approved now.

**Pull request closed without merging**
