### PR TITLE
added cmake minumim required version and protobuf static lib link (#201)

### PR DESCRIPTION
**Pull request by schilasky**

### CODE REVIEW

**Comment by FlorianReimold** [comment]
Tried to compile person_snd on Windows 10 and Ubuntu 18.04 (CMake 3.10). Both worked out of the box.

**Comment by FlorianReimold** [comment]
Additional Note: CMake 3.5 (from Ubuntu 16.04) fails to compile the samples. I used eCAL 5.8.3 from the PPA for that. Maybe we should state CMake 3.10 as minimum required version instead of 3.0. After Upgrading CMake to 3.13 (also from the PPA), person_snd compiles without issues.

**Comment by FlorianReimold** [comment]
Looks good. When I now try to compile person_snd with stock CMake on Ubuntu 16.04, I get a proper error message.

```
CMake Error at CMakeLists.txt:19 (cmake_minimum_required):
  CMake 3.10 or higher is required.  You are running version 3.5.1


-- Configuring incomplete, errors occurred!
```

After upgrading CMake to 3.13, CMaking works fine. However the CMakeLists.txt still lacks the C++14 compiler setting:

``` cmake
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

Do we want to include that as well? It is not need for Ubuntu 18.04 (gcc 7) any more, but gcc 5 will complain about the `auto` keyword, as it is set to c++98 by default. For that reason, the [Hello World example](https://continental.github.io/ecal/getting_started/hello_world.html#hello-world-publisher) states to explicitely set the C++ standard in the CMakeLists.txt.

**Comment by rex-schilasky** [comment]
@FlorianReimold thanks for testing. I would not add extra lines to support Ubuntu 16.04. This can be skipped for that specific improvement to build samples standalone.

**Pull request merged**
