### PR TITLE
Add ros2 msg reflection plugin to ecal_mon_gui.

### PR DESCRIPTION
**Pull request by ZhenshengLee**
---
name: Pull request
about: Create a pull request for this project
title: Add ros2 msg reflection plugin to ecal_mon_gui
labels: ''
assignees: ''

---

**Pull request type**

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

**What is the current behavior?**

Issue Number:  https://github.com/continental/rmw_ecal/issues/18#issue-929783852

- The ecal app tool does not have a good support to ros2 system.
- rmw_ecal_dynamic_cpp does not support ros2cli like `ros2 topic echo`
- 

**What is the new behavior?**

- You can view some ros2 msgs through ecal_mon_gui
- It can be a tool that replaces `ros2 topic echo`

image

**Does this introduce a breaking change?**

- [x] Yes
- [ ] No

**Other information**

As for now, it is still a demo case and may not be merged into the official repo.

Feel free to give me feedback. 

Thanks.

### CODE REVIEW

**Comment by rex-schilasky** [comment]
First of all thank you for contributing. As you said it's more a prototype and needs some more work. I checked your implementation and it is specifically supporting 2 message types for now. Is there any kind of a more generic approach to dynamically reflect the content of ROS message types ? I don't think so, but wanted to be sure I did not miss something.

**Comment by ZhenshengLee** [comment]
> First of all thank you for contributing. As you said it's more a prototype and needs some more work. I checked your implementation and it is specifically supporting 2 message types for now. Is there any kind of a more generic approach to dynamically reflect the content of ROS message types ? I don't think so, but wanted to be sure I did not miss something.

@rex-schilasky 

Perhaps rmw_ecal can help to get msg type info from the given parameters including type name and node name.
As for now, many `if` statements will be an ugly solution for echo ros2 msgs.
I'll push more commits, and before that this pr will be a draft.

Thanks.

**Comment by brakmic-aleksandar** [comment]
Hmm, maybe rmw_ecal could provide API for deserialization of messages, but the plugin itself will have to provide filled rosidl_typesupport_introspection_cpp::MessageMembers or rosidl_typesupport_introspection_c__MessageMembers with metadata of messages.

**Comment by rex-schilasky** [comment]
@ZhenshengLee what is the reason to not use rosidl_typesupport_protobuf + rmw_ecal and then to use the eCALMon builtin reflection for the protobuf message format. With that solution would have a generic reflection for all ROS messages.

**Comment by ZhenshengLee** [comment]
> @ZhenshengLee what is the reason to not use rosidl_typesupport_protobuf + rmw_ecal and then to use the eCALMon builtin reflection for the protobuf message format. With that solution you would have a generic reflection for all ROS messages.

You are right, but currently there is an issue of runtime crash. https://github.com/continental/rmw_ecal/issues/19

According to https://github.com/continental/ecal/issues/115 ecal is designed as a middleware and is not domain specific.

So there are things to do to get "rosidl_typesupport_protobuf + rmw_ecal" used with comfort in ROS2 , like rviz support.

RViz will stuck now with rmw_ecal running currently.

BTW, ptotobuf serialization may makes it easier to connect apollo cyber and ros2.

Thanks.

**Comment by rex-schilasky** [comment]
Okay, so we need to fix that issue in rmw_ecal first, Aleks is working on it. Regarding protobuf I fully agree. If you record ROS2 messages with eCALRec into HDF5 container, serialized as protobuf you have lots of new options:

* eCALRec can record distributed on multiple hosts using shm ipc only
* the performance is often limited by the mass storage throughput only (currently we run a project that is recording 4 cameras 8M with 30 fps with zero loss of frames, its about 900 MB/s on that host, other host doing their own measurements in parallel)
* the reuse / compatibility of that kind of HDF5 / protobuf measurements is guaranteed for a long time, even message schemas are changing slightly, this is reducing cost for transforming or rerecording dramatically

**Comment by ZhenshengLee** [comment]
> @ZhenshengLee: I found an interesting discussion at ROS discourse regarding ROS2 type support introspection [here](https://discourse.ros.org/t/ros-2-type-support-introspection-and-conversion-of-c-c-messages-to-from-yaml/22295). Seems to me a generic approach to convert a ROS2 message to a YAML representation. This YAML could be shown a a simple string in an eCALMon plugin, couldn't it ?

@rex-schilasky 

Thanks for your report, I checked the [doc](https://github.com/christophebedard/dynamic_message_introspection/blob/add-cpp-support-and-refactor/dynmsg_demo/README.md) and It
> do dynamic introspection of messages using the rcl message API

As the usability of rcl api depends on rmw api, and then the implementation of rmw, due to lack of enough rmw api support of rmw_ecal, for example `rcl_get_publishers_info_by_topic` or `rmw_get_publishers_info_by_topic`, this demo will get compiled or work.

I already created an issue about lack of rmw api support, check https://github.com/continental/rmw_ecal/issues/18 , which has caused most of ros2 tools unavailable.

Currently this PR only uses msg definition hpp and helper functions and does not depend on rmw.

**Comment by rex-schilasky** [comment]
We should discuss to close the PR .. to have a ROS message reflection seems to be a very specific use case to me, most of the users seems to use eCAL with protobuf or ROS and it's message system.

@ZhenshengLee can you please work on that feature isolated ? If there is a ROS concept for doing generic reflection like google protobuf is able to do we can easily create a monitor plugin out of it to support such a feature.

**Pull request closed without merging**
