### PR TITLE
Add Conan integration

### PR DESCRIPTION
**Pull request by NewProggie**
This is the first of a series of follow-up commits to add Conan integration to the eCAL Open Source project

### CODE REVIEW

**Comment by rex-schilasky** [comment]
Hi Kai, thank you for starting to fix the thirdparty integration via Conan (#11). Great !

**Comment by NewProggie** [comment]
Hi eCAL'ers,

any chance we can add my changes to `.appveyor.yml` and `.travis.yml` already into master branch? I've tried changing the CI configuration to be using Conan already. However, both Appveyor as well as Travis CI always seem to be using the original CI config files from master branch instead of the ones, I've changed in this branch `feature/add_conan_integration`.
Note that, the same holds true even for my own fork, which in itself is kind of curious.

**Comment by rex-schilasky** [comment]
> Hi eCAL'ers,
> 
> any chance we can add my changes to `.appveyor.yml` and `.travis.yml` already into master branch? I've tried changing the CI configuration to be using Conan already. However, both Appveyor as well as Travis CI always seem to be using the original CI config files from master branch instead of the ones, I've changed in this branch `feature/add_conan_integration`.
> Note that, the same holds true even for my own fork, which in itself is kind of curious.

Can you bring these changes in a separate PR ?

**Comment by NewProggie** [comment]
Alright, so, I've removed all Conan specific adjustments for your project's CMake configuration as I was unable to convince AppVeyor and Travis to use my modified versions from this branch.
Please feel free to merge this PR for now and I'll add another one for CMake/CI specific adjustments.

**Comment by rex-schilasky** [comment]
Great job ! Thank you @NewProggie !

**Pull request merged**
